services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: solicitacao_egpce_app
    working_dir: /var/www
    user: "www-data"
    volumes:
      - ./:/var/www
    depends_on:
      - db
      - redis
    networks:
      - solicitacao_egpce

  nginx:
    image: nginx:alpine
    container_name: solicitacao_egpce_nginx
    ports:
      - "8036:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - solicitacao_egpce

  db:
    image: postgres:16-alpine
    container_name: solicitacao_egpce_db
    environment:
      POSTGRES_DB: solicitacao_egpce
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      TZ: America/Fortaleza
    ports:
      - "8037:5432"
    volumes:
      - solicitacao_egpce_db:/var/lib/postgresql/data
    networks:
      - solicitacao_egpce

  redis:
    image: redis:alpine
    container_name: solicitacao_egpce_redis
    ports:
      - "8038:6379"
    networks:
      - solicitacao_egpce

networks:
  solicitacao_egpce:

volumes:
  solicitacao_egpce_db: